name: Linting the code

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        # We need to fetch all branches and commits so that `nx affected` has a base to compare against.
        fetch-depth: 0

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2
      with:
        main-branch-name: 'develop'

    - name: Install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: ">=20.15.0"

    - name: Install dependencies
      run: npm ci

    - name: Lint typescript
      run: npx nx affected --target=lint

    - name: Lint styles
      run: npx nx affected --target=stylelint